// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfXXd6jc8Cth9SAYsGi5nZIOSUuUoSQjo',
    appId: '1:663533064281:web:281ce7cd3e7fe6ae682148',
    messagingSenderId: '663533064281',
    projectId: 'electrohub-6dfeb',
    authDomain: 'electrohub-6dfeb.firebaseapp.com',
    databaseURL: 'https://electrohub-6dfeb-default-rtdb.firebaseio.com',
    storageBucket: 'electrohub-6dfeb.appspot.com',
    measurementId: 'G-30W7DYRTTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnUzkerYuOoJzy1h0QOMO9_hJFmdenCYc',
    appId: '1:663533064281:android:5a1ce89f726f6d35682148',
    messagingSenderId: '663533064281',
    projectId: 'electrohub-6dfeb',
    databaseURL: 'https://electrohub-6dfeb-default-rtdb.firebaseio.com',
    storageBucket: 'electrohub-6dfeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYEFZHrwM5li5P54kSOVbwybGia8JU3f4',
    appId: '1:663533064281:ios:d2af3e2ddf25ab8f682148',
    messagingSenderId: '663533064281',
    projectId: 'electrohub-6dfeb',
    databaseURL: 'https://electrohub-6dfeb-default-rtdb.firebaseio.com',
    storageBucket: 'electrohub-6dfeb.appspot.com',
    iosBundleId: 'com.example.eWaris',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZkYr9IfEOcG3fSPnvmZH1ZAdjTogFUB0',
    appId: '1:663533064281:web:48fd453a201140ae682148',
    messagingSenderId: '663533064281',
    projectId: 'electrohub-6dfeb',
    authDomain: 'electrohub-6dfeb.firebaseapp.com',
    databaseURL: 'https://electrohub-6dfeb-default-rtdb.firebaseio.com',
    storageBucket: 'electrohub-6dfeb.appspot.com',
    measurementId: 'G-ZRPGXG91TQ',
  );
}
